df = pd.read_csv('nodes_by_class.csv',sep='\t')
df.groupby('modularity_class').count()
#filter out classes with less than a threshold of members
df = df[df['modularity_class'].isin([2,3,4,5,7,11])]

two = df[df['modularity_class'] == 2]
list(two['id']) #prints the following:
#religion
#brown
'''
['Anglicanism',
 "Bah\xc3\xa1'\xc3\xad Faith",
 'Christianity',
 'Epistle to the Hebrews',
 'Judaism',
 'Eusebius',
 'Epistle of James',
 'David',
 'Holy Spirit',
 'Clement of Alexandria',
 'Books of the Bible',
 'Augustine of Hippo',
 'Christology',
 'Epistle to Philemon',
 'Barnabas',
 'Hebrew calendar',
 'Calvinism',
 'Bible',
 'Garden of Eden',
 'Immaculate Conception',
 'First Vatican Council',
 'Anglican Communion',
 'Bernard of Clairvaux',
 'Council of Trent',
 'Cetus',
 'Evangelicalism',
 'Constantius II',
 'Egalitarianism',
 'Conservative Judaism',
 'Abraham',
 'Book of Genesis',
 'Acts of the Apostles',
 'Gospel of John',
 'Heaven',
 'Epistle to the Romans',
 'Irenaeus',
 'Gospel',
 'Gospel of Luke',
 'Gold',*************************************
 'Ephrem the Syrian',
 'Book of Exodus',
 'Eastern Orthodox Church',
 'Easter',
 'Diatessaron',
 'Aramaic language',
 'Gnosticism',
 'Arianism',
 'Coptic Orthodox Church of Alexandria',
 'Book of Nehemiah',
 'Book of Esther',
 'Books of Chronicles',
 'Book of Ezra',
 'Huldrych Zwingli',
 'Iconoclasm',
 'Eucharist',
 "Apostles' Creed",
 'Gospel of Matthew',
 'Dominican Order',
 'Anabaptists',
 'Hebrew language',
 'Icon',
 'The Church of Jesus Christ of Latter-day Saints',
 'Hasidic Judaism',
 'Christmas',
 'Book of Daniel',
 'Hezekiah',
 'Books of Kings',
 'Galilee',
 'Book of Proverbs',
 'Halakha',
 'Book of Jeremiah',
 'First Council of Constantinople',
 'First Epistle to the Corinthians',
 'Eusebius of Nicomedia',
 'Christadelphians',
 'First Council of Nicaea',
 'Athanasius of Alexandria',
 'Athanasian Creed',
 'Books of Samuel',
 'Book of Judges',
 'History of ancient Israel and Judah',
 'Book of Joshua',
 'Bethlehem',
 'Ark of the Covenant',
 'Book of Ruth',
 'Ignatius of Antioch',
 'Ecumenical council',
 'Christendom',
 'Council of Constance',
 'Cardinal (Catholicism)',
 'Fourth Council of the Lateran',
 'Canon law',
 'Council of Chalcedon',
 'Book of Job',
 'Ecclesiastes',
 'Christ',
 'Historicism',
 'Book of Mormon',
 'Dualism',
 'Grape',**************************************************
 'Fruit',**************************************************
 'Epistle to the Philippians',
 'Epistle to the Ephesians',
 'Gospel of Mark',
 'Elijah',
 'Book of Revelation',
 'Domitian',
 'Anthony the Great',
 'Ambrose',
 'Book of Ezekiel',
 'Canonization',
 'Allah',
 'Baptists',
 'Ezekiel',
 'Isaiah',
 'Epistle to Titus',
 'Ephesus',
 'Epistle to the Galatians',
 'Apostolic succession',
 'Anointing of the Sick',
 'Baptism',
 'Dead Sea',
 'Constantine the Great',
 'Constantine II (emperor)',
 'Aaron',
 'Book of Numbers',
 'Isaac',
 'Book of Jonah',
 'Book of Micah',
 'Book of Obadiah',
 'Docetism',
 'Giovanni Pierluigi da Palestrina',
 'Isidore of Seville',
 'Augustine of Canterbury',
 'Gregory of Nazianzus',
 'Church of the Holy Sepulchre',
 'Book of Deuteronomy',
 'Ammon',
 'Ahab',
 'Hadith',
 'Aries (constellation)',
 'Capricornus',
 'Aquarius (constellation)',
 'Inquisition',
 'Andrew Carnegie',
 'Book of Habakkuk',
 'Catharism',
 'Hildegard of Bingen',
 'Abbot',
 'Epistle to the Colossians',
 'Book of Zechariah',
 'First Epistle to the Thessalonians',
 'Book of Haggai',
 'Apocrypha',
 'Book of Hosea',
 'Book of Lamentations',
 'Book of Isaiah',
 'First Epistle of Peter',
 'Book of Amos',
 'Epistle of Jude',
 'Book of Malachi',
 'Book of Joel',
 'Book of Zephaniah',
 'Creation myth',
 'Death',
 'Amazing Grace',
 'Doctrine and Covenants',
 'Cyril of Jerusalem',
 'Herman Melville',
 'Absalom',
 'Hanukkah',
 'Halloween',
 'Giordano Bruno',
 'Congregationalist polity',
 'Esther',
 'Brigham Young',
 'Christian eschatology',
 'Cetacea',
 'Christian Church (Disciples of Christ)',
 'Benedict of Nursia',
 'Ansgar',
 'Order of Saint Benedict',
 'Cyril of Alexandria',
 'Altruism',
 'Christmas tree',
 'Episcopal polity',
 'Bishop',
 'Fra Angelico',
 'Francis of Assisi',
 'Christian mythology',
 'Filioque',
 'History of Christianity',
 'Islamic eschatology',
 'Constans',
 'Andrew II of Hungary',
 'Creationism',
 'Desiderius Erasmus',
 'Hosea',
 'Ezra',
 'Haggai',
 "`Abdu'l-Bah\xc3\xa1",
 'Eugene, Oregon',
 'Armageddon',
 'Devil',
 'Eschatology',
 'Columbanus']
 '''

 two = df[df['modularity_class'] == 3]
 list(two['id']) #prints the following:
 #science
 #yellow
 '''
 ['British Columbia',**************************************
 'Canadian Pacific Railway',
 'Godzilla',
 'CANDU reactor',
 'Germanium',
 'Alaska',
 'International Space Station',
 'Hypoxia (medical)',
 'Carbon monoxide',
 'Infrared spectroscopy',
 'Big Bang',
 'Carbon',
 'Hydrogen',
 'Hipparchus',
 'Apparent magnitude',
 'Cambrian',
 'Devonian',
 'Geologic time scale',
 'Alternative medicine',
 'Canadian Shield',
 'Alberta',
 'Albertus Magnus',
 'Food preservation',
 'Electric charge',
 'International Astronomical Union',
 'Earth',
 'Extraterrestrial life',
 'Engineering',
 'Food and Drug Administration',
 'Anatomy',
 'Cell nucleus',
 'Cell biology',
 'Cretaceous',
 'Amphibian',
 'Covalent bond',
 'Erwin Schr\xc3\xb6dinger',
 'Frederick Soddy',
 'Chemical bond',
 'Chemical element',
 'Beta decay',
 'Chemical reaction',
 'Brownian motion',
 'Botany',
 'Irving Langmuir',
 'Alpha decay',
 'Henry Moseley',
 'Bose\xe2\x80\x93Einstein condensate',
 'Bohr model',
 'Ferromagnetism',
 'Atomic orbital',
 'Helium',
 'International Union of Pure and Applied Chemistry',
 'Albert Einstein',
 'Ernest Rutherford',
 'Holocene',
 'Bayer designation',
 'Physical cosmology',
 'Copenhagen interpretation',
 'David Deutsch',
 'EPR paradox',
 'Density',
 'Acoustics',
 'Coriolis force',
 'Electromagnetism',
 'Chemistry',
 'Carl Linnaeus',
 'British thermal unit',
 'Heinrich Hertz',
 'Electromagnetic radiation',
 'Impact crater',
 'Carbon dioxide',
 'Columbia River',
 'David Thompson (explorer)',
 'Biosphere',
 'Challenger Deep',
 'Diamond',
 'Antoine Lavoisier',
 'Insulator (electricity)',
 'Centaurus',
 'Hamiltonian (quantum mechanics)',
 'Feynman diagram',
 'Alessandro Volta',
 'Alexander of Aphrodisias',
 'DNA',
 'International Council for Science',
 'Fox News Channel',
 'Carina (constellation)',
 'Fantastic Four',
 'Iodine',
 'Ammonia',
 'Chlorine',
 'Alchemy',
 'Avicenna',
 'Iron',
 'BASE jumping',***************************************
 'Apiales',
 'Apiaceae',
 'Cellulose',
 'Electricity',
 'Ecology',
 'Electromagnetic spectrum',
 'Developmental biology',
 'Evolution',
 'DDT',
 'Hippocrates',
 'Ethology',
 'Ernst Haeckel',
 'Controlled Substances Act',
 'MDMA',
 'Cognitive behavioral therapy',
 'Cyclic adenosine monophosphate',
 'Chemical equilibrium',
 'Denaturation (biochemistry)',
 'Fundamental interaction',
 'Galen',
 'Cathode ray tube',
 'Electron microscope',
 'Cardiology',
 'Asteroid',
 'Idaho',**********************************
 'Argo Navis',
 'Crux',
 'Altair',
 'Edwin Hubble',
 'Carl Sagan',
 'Humphry Davy',
 'History of science',
 'Friedrich W\xc3\xb6hler',
 'Damascus steel',
 'Francis Crick',
 'Gregor Mendel',
 'Darwinism',
 'Charles Lyell',
 'Apollo 8',
 'DNA replication',
 'Cell (biology)',
 'Eocene',
 'Aluminium',
 'Haber process',
 'Gilbert N. Lewis',
 'Deuterium',
 'Electronvolt',
 'Canidae',
 'Alpha Centauri',
 'Geology',
 'Apollo program',
 'Ernst Mayr',
 'Cladistics',
 'Dinosaur',
 'Folklore',*********************************
 'Bioinformatics',
 'Common descent',
 'Distillation',
 'Bear',
 'HIV',
 'Imhotep',
 'Honolulu',
 'Electrical engineering',
 'Intelsat',
 'Electronegativity',
 'Claude Louis Berthollet',
 'Charge-coupled device',
 'BCS theory',
 'Chordate',
 "Hudson's Bay Company",
 'Felidae',
 'Conversion of units',
 'Actinopterygii',
 'Histology',
 'E. O. Wilson',
 'Alfred Russel Wallace',
 'Erasmus Darwin',
 'Augustin-Jean Fresnel',
 'Inflation (cosmology)',
 'Astronomical unit',
 'Bigfoot',**********************************
 'Adenosine triphosphate',
 'Canadian English',
 'Edgar Rice Burroughs',
 'Calcium',
 'Glucose',
 'Combustion',
 'Chemotherapy',
 'Down syndrome',
 'Arizona State University',
 'Electrochemistry',
 'Anthropology',
 'Electric current',
 'Infrared',
 'DNA ligase',
 'California Institute of Technology',
 'Diffraction',
 'Interference (wave propagation)',
 'Cloning',
 'Southeast Alaska',
 'Endocrine system',
 'Endocrinology',
 'Antioxidant',
 'Insulin',
 'Astrobiology',
 'Biochemistry',
 'Fermi paradox',
 'Antibody',
 'Genetic disorder',
 'Heredity',
 'Enrico Fermi',
 'Acceleration',
 'Genetics',
 'Drosophila',
 'Genetic engineering',
 'Diagnostic and Statistical Manual of Mental Disorders',
 'Golgi apparatus',
 'Enterobacteriaceae',
 'Gram-negative bacteria',
 'Ester',
 'Amide',
 'Elementary particle',
 'Apollo 11',
 'Eugene Wigner',
 'Gustav Kirchhoff',
 'Canadian Radio-television and Telecommunications Commission',
 'Cenozoic',
 'Gestation',
 'Antimony',
 'Europium',
 'Boron',
 'Arsenic',
 'Bipolar disorder',
 'Graph theory',**********************************
 'Ediacaran',
 'Freeman Dyson',
 'Godzilla (1954 film)',*****************************
 'Francium',
 'Caesium',
 'Major depressive disorder',
 'Albinism',
 'Arctic fox',
 'Carnivora',
 'Emil Kraepelin',
 'Horse',
 'Bird',
 'Fossil',
 'Chondrichthyes',
 'Flamsteed designation',
 'Cadmium',
 'Chromium',
 'Beryllium',
 'Energy',
 'Double-slit experiment',
 'Andr\xc3\xa9-Marie Amp\xc3\xa8re',
 'Electron',
 'Ethanol',
 'Acid',
 'Catalysis',
 'Harrison Schmitt',
 'Apollo 15',
 'Apollo 17',
 'Galileo (spacecraft)',
 'Glenn T. Seaborg',
 'Central nervous system',
 'Deccan Traps',
 'Genetically modified organism',
 'Robert Koch',
 'Immune system',
 'Hydra (genus)',
 'Graphite',
 'Biological membrane',
 'Carbohydrate',
 'Apollo 13',
 'Chlorophyta',
 'Geiger counter',
 'Hydrophobe',
 'Asexual reproduction',
 'Apollo 14',
 'Apollo 16',
 'Apollo 12',
 'Apollo 10',
 'Extravehicular activity',
 'Apollo 1',
 'Apollo 9',
 'Apollo 7',
 'Americium',
 'Boiling point',
 'Archaeopteryx',
 'Aromatic hydrocarbon',
 'Immunology',
 'Analytical chemistry',
 'Intermolecular force',
 'John Ray',
 'Alkene',
 'Amine',
 'Burgess Shale',
 'Glycine',
 'Amino acid',
 'Conspiracy theory',
 'Explosive material',
 'Fred Hoyle',
 'G protein',
 'Galaxy']
 '''
two = df[df['modularity_class'] == 4]
list(two['id']) #prints the following:
#America
#earthy-red
'''
['American Civil War',
 'Chicago',
 'American Civil Liberties Union',
 'Franklin D. Roosevelt',
 'Bill Clinton',
 'Allen Ginsberg',
 'Contras',
 'Herbert Hoover',
 'Arkansas',
 'George H. W. Bush',
 'Executive Order 9066',
 'Henry Ford',
 'Federal Reserve System',
 'General Motors',
 'General Electric',
 'Houston',
 'American Revolutionary War',
 'Charles Baudelaire',
 'BMW',
 'British Airways',
 'Charlie Chaplin',
 'Andy Warhol',
 'Ice hockey',
 'Columbia University',
 'Formula One',
 'Colorado',
 'Elvis Presley',
 'Detroit',
 'Hamilton, Ontario',
 'Illinois',
 'Great Lakes',
 'Henry Kissinger',
 'Honda',
 'Bastille Day',
 'Baltimore Orioles',
 'Hit (baseball)',
 'Atlanta Braves',
 'Barry Bonds',
 'Hank Aaron',
 'Babe Ruth',
 'Centers for Disease Control and Prevention',
 'California',
 'Isaac Asimov',
 'Art Deco',
 'A. E. van Vogt',
 'Harlan Ellison',
 'Gene Roddenberry',
 'Alfred Korzybski',
 'Hugo Gernsback',
 'Cambridge, Massachusetts',
 'French cuisine',
 'Grover Cleveland',
 'Fields Medal',
 'George Washington',
 'Connecticut',
 'Dartmouth College',
 'French Revolution',
 'Alfred Hitchcock',
 'Alabama',
 'Academy Awards',
 'Dmitri Shostakovich',
 'Boeing 747',
 'Gettysburg Address',
 'Battle of Gettysburg',
 'Abraham Lincoln',
 'Emancipation Proclamation',
 'Confederate States of America',
 'First Lady of the United States',
 'American Revolution',
 'Buckminster Fuller',
 'Greenwich Village',
 'American English',
 'Chicago Bears',
 'City',
 'Fr\xc3\xa9d\xc3\xa9ric Chopin',
 'Elie Wiesel',
 'City University of New York',
 'Barnard College',
 'Basketball',
 'Giuseppe Verdi',
 'Grand Guignol',
 'Channel 4',
 'Doris Day',
 'Full Metal Jacket',
 'Cult film',
 'Frank Herbert',
 'H. R. Giger',
 'David Lynch',
 'David Bowie',
 'Dada',
 'Donald Rumsfeld',
 'Dwight D. Eisenhower',
 'American Airlines Flight 77',
 'Edwin Howard Armstrong',
 'Bing Crosby',
 'Frederik Pohl',
 'Futurians',
 'Carolina Panthers',
 'DC Comics',
 'Detroit Red Wings',
 'Chrysler',
 'Alain Connes',
 'Francis Ford Coppola',
 'Aircraft hijacking',
 'Broadway (Manhattan)',
 'Civilian Conservation Corps',
 'Colin Powell',
 'Black Sabbath',
 'Howard Hughes',
 'Concorde',
 'Frank Lloyd Wright',
 'Cleveland Indians',
 'Effects unit',
 'Eric Clapton',
 'Electric guitar',
 'Bass guitar',
 'Frank Zappa',
 'Dayton, Ohio',
 'Human sexual activity',
 'Film editing',
 'James Cameron',
 'George Lucas',
 'Blade Runner',
 'Cable television',
 'Britney Spears',
 'Fontainebleau',
 'Eiffel Tower',
 'Heathrow Airport',
 'Indianapolis Colts',
 'Hoover Dam',
 'Federal Aviation Administration',
 'Benjamin Franklin',
 'Franz Boas',
 'Calvin Coolidge',
 'Andr\xc3\xa9 Weil',
 'Alexander Grothendieck',
 'Columbus, Ohio',
 'Cheers',
 'Frasier',
 'Boston Red Sox',
 'Immigration to the United States',
 'Cotton Mather',
 'Django Reinhardt',
 'Colorado Springs, Colorado',
 'Fort Collins, Colorado',
 'Dr. Strangelove',
 'Groucho Marx',
 'Ann Arbor, Michigan',
 'International Mathematical Union',
 'Arnold Schwarzenegger',
 'Hank Greenberg',
 'Iowa State University',
 'Arizona Cardinals',
 'American Football League',
 'Arizona Diamondbacks',
 'Denver Broncos',
 'Houston Texans',
 'Green Bay Packers',
 'Dallas Cowboys',
 'Cuban Missile Crisis',
 'American Airlines',
 'Ithaca, New York',
 'Cleveland',
 'Ivy League',
 'Ithaca College',
 'Erie Canal',
 'Buffalo, New York',
 'Finger Lakes',
 'Federal Bureau of Investigation',
 'Citizen Kane',
 'Cahiers du cin\xc3\xa9ma',
 'Ingmar Bergman',
 'Fran\xc3\xa7ois Truffaut',
 'Cecil B. DeMille',
 'Brian De Palma',
 'Governor of New York',
 'Dziga Vertov',
 'Gioachino Rossini',
 'American Film Institute',
 'D. W. Griffith',
 'Frank Capra',
 'Fritz Lang',
 'Akira Kurosawa',
 'Andrei Tarkovsky',
 'Articles of Confederation',
 'Andrew Johnson',
 'The Bronx',
 'Charles Evans Hughes',
 'Hunter College',
 'Golden Gate Bridge',
 'Flag of the United States',
 'Double bass',
 'Drum kit',
 'Elvis Costello',
 'Hawkwind',
 'Evil Dead II',
 'Army of Darkness',
 'Gary, Indiana',
 'Brown University',
 'Fenway Park',
 'Chicago White Sox',
 'Colorado Rockies',
 'Cincinnati Reds',
 'Chicago Cubs',
 'National Baseball Hall of Fame and Museum',
 'Boston Herald',
 'Blue \xc3\x96yster Cult',
 'Heavy metal music',
 'Ice-T',
 'Fleetwood Mac',
 'Electric Light Orchestra',
 'Christopher Guest',
 'Billy Crystal',
 'Chuck Yeager',
 'Distinguished Service Medal (U.S. Army)',
 'Bronze Star Medal',
 'Boeing B-17 Flying Fortress',
 'Atlanta',
 'Choctaw',
 'Andrew Jackson',
 'Boeing 767',
 'B. F. Skinner',
 'Alban Berg',
 'Chief of Naval Operations',
 'Garrison Keillor',
 'Guitar',
 'Country music',
 'Abner Doubleday',
 'Gary Snyder',
 'Barry Goldwater',
 'Impressionism',
 '\xc3\x89douard Manet',
 'Claude Debussy',
 'Auguste Rodin',
 'Berthe Morisot',
 'Camille Pissarro',
 'Erik Satie',
 'Claude Monet',
 'Diesel engine',
 'George Harrison',
 'Buddy Holly',
 'Frank Sinatra',
 'Chet Atkins',
 'Ben Bova',
 'Denver',
 'Dolly Parton',
 'Heckler &amp; Koch MP5',
 'Delaware',
 'Deism',
 'Carl Barks',
 'Al Capone',
 'African Americans',
 'Frederick Douglass',
 'Ig Nobel Prize',
 'Gone with the Wind',
 'The Birth of a Nation',
 'David Mamet',
 'Cuisine of the United States',
 'Deus Ex',
 'Ernest Hemingway',
 'Film noir',
 'David Fincher',
 'Dr. Dre',
 'Doppler effect',********************************************
 'Auto racing',
 'Bugatti',
 'Calvin and Hobbes',
 'Bill Watterson',
 'Chuck Jones',
 'Doonesbury',
 'David Cronenberg',
 'Blue Velvet (film)',
 'Harry Shearer',
 'Garry Trudeau',
 'Atlanta Falcons',
 'Buffalo Bills',
 'Baltimore Ravens',
 'Detroit Lions',
 'Cleveland Browns',
 'Cincinnati Bengals',
 'Chlamydia infection',
 'Anti-Ballistic Missile Treaty',
 'Colette',
 'The Alan Parsons Project',
 'Chuck D',
 'Grateful Dead',
 'Charlize Theron',
 'Cordwainer Smith',
 'Beastie Boys',
 'Halle Berry',
 'Dr. Seuss',
 'Andrew Wiles',
 'American Football Conference',
 'Cyberpunk',
 'Bruce Sterling',
 'Ghost in the Shell',
 'John Woo',
 'Batman (1989 film)',
 'Chariots of Fire',
 'Federico Fellini',
 'Humphrey Bogart',
 'The Beach Boys',
 'Arc de Triomphe',
 'Davenport, Iowa',
 'Detroit Tigers',
 'Devo',
 'Electronic music',
 'Ellis Island',
 'Charles Mingus',
 'Henry Rollins',
 'Jazz',
 'Dave Brubeck',
 'Electronic oscillator',
 'Empire State Building',
 'David Letterman',
 'Danny Kaye',
 'Brigitte Bardot',
 'Ira Gershwin',
 'George Gershwin',
 'Baseball',
 'Friends',
 'Dead Kennedys',
 'Gotham City',
 'Batman Returns',
 'Batman',
 'Batman &amp; Robin (film)',
 'Batman Forever',
 'Danny Elfman',
 'Freemasonry',
 'Cy Young Award',
 'Home run',
 'Arlo Guthrie',
 'Georges Braque',
 'Clay Mathematics Institute',
 'Ferrari',
 'Dorothy Parker',
 'Drew Barrymore',
 'Burt Lancaster',
 'Fawlty Towers',
 'Historical revisionism',
 'Blues',
 'Des Moines, Iowa',
 'Dewey Decimal Classification',
 'Jacques-Louis David',
 'Edvard Munch',
 'French Republican Calendar',
 'Howard Hawks',
 'George Washington Carver',
 'BDSM',*****************************************
 'Camp David',
 'Bob Wills',
 'Ernest Thayer',
 'Frankie Goes to Hollywood',
 'I. M. Pei',
 'Declaration of the Rights of Man and of the Citizen',
 'Dennis Hopper',
 'Canadian football',
 'Central Pacific Railroad',
 'Associate Justice of the Supreme Court of the United States',
 'Chapter 11, Title 11, United States Code',
 'Enron',
 'Major League Baseball Most Valuable Player Award',
 'American League Championship Series',
 'Houston Astros',
 'Miami Marlins',
 'Gustave Eiffel',
 'Gorillaz',
 'Hammond organ',
 'Carlo Goldoni',
 'BBC Radio 1',
 'First National Pictures',
 'Gene Kelly',
 'House music',
 'Major League Baseball Rookie of the Year Award',
 'National League Division Series',
 'Bud Selig',
 'Compact disc',
 'Cy Young']
 '''

two = df[df['modularity_class'] == 5]
list(two['id']) #prints the following:
#result is philosophy and mythology rolled into one
#light pink
'''
['Capitalism',
 'Bertrand Russell',
 'Greek drachma',
 'David D. Friedman',
 'Economics',
 'Friedrich Hayek',
 'Adam Smith',
 'Fluid dynamics',
 'Agnosticism',
 'Francis Bacon',
 'Fr\xc3\xa9d\xc3\xa9ric Bastiat',
 'Immanuel Kant',
 'Political freedom',
 'Cantor set',
 'Archimedes',
 'Athens',
 'Georg Cantor',
 'Charles Sanders Peirce',
 'Edmund Husserl',
 'David Hilbert',
 'Euclidean space',
 'Aristotle',
 'George Berkeley',
 'Cardinality',
 'Homer',
 'Enlil',
 'Hesiod',
 'Eos',
 'Diana (mythology)',
 'Cerberus',
 'Isaac Newton',
 'Gottfried Wilhelm Leibniz',
 'Cauchy sequence',
 'Great Vowel Shift',
 'Falsifiability',
 'Aerodynamics',
 'Anarchism',
 'Individualism',
 'Giovanni Boccaccio',
 'Hecate',
 'Aeschylus',
 'Hermes',
 'Acropolis',
 'Crete',
 'Baruch Spinoza',
 'Herodotus',
 'Classics',
 'Goddess',
 'David Hume',
 'Dianic Wicca',
 'Douglas Hofstadter',
 'Daniel Dennett',
 'Fyodor Dostoyevsky',
 'Franz Kafka',
 'Hahn\xe2\x80\x93Banach theorem',
 'Aristophanes',
 'Aegina',
 'Euripides',
 'Delphi',
 'Hades',
 'Hercules',
 'Delian League',
 'Heracles',
 'Athenian democracy',
 'Gylfaginning',
 'Baldr',
 'Fenrir',
 'Frigg',
 'Hera',
 'Aeneas',
 'Ennius',
 'Bayesian probability',
 'The Trial',
 'Fire (classical element)',
 'Earth (classical element)',
 'Empedocles',
 'Water (classical element)',
 'Air (classical element)',
 'Artemis',
 'Aleister Crowley',
 'Demeter',
 'Idealism',
 'Cicero',
 'Anaximenes of Miletus',
 'Heraclitus',
 'Democritus',
 'Anaximander',
 'Heinrich Schliemann',
 'Blaise Pascal',
 'Bo\xc3\xb6tes',
 'Denis Diderot',
 'Historiography',
 'Series (mathematics)',
 'Euclid',
 'Hermann Hesse',
 'Anubis',
 'Apuleius',
 'Claudius Aelianus',
 'Anaxagoras',
 'Epicurus',
 'Friedrich Nietzsche',
 'Dante Alighieri',
 'The Canterbury Tales',
 'Ayn Rand',
 'Ancient philosophy',
 'Geoffrey Chaucer',
 'Corinth',
 'Edna St. Vincent Millay',
 'Eris (mythology)',
 'Aphrodite',
 'Achaeans (Homer)',
 'Hephaestus',
 'Ares',
 'Achilles',
 'Erinyes',
 'Athena',
 'A. J. Ayer',
 'Epistemology',
 'Frederick Copleston',
 'Alhazen',
 'John Stuart Mill',
 'Acropolis of Athens',
 'Planned economy',
 'David Ricardo',
 'Gerolamo Cardano',
 'Catullus',
 'Horace',
 'German literature',
 'Chaos theory',
 'Don Quixote',
 'Emma Goldman',
 'Anarcho-capitalism',
 'Hedonism',
 'Hausdorff space',
 'Archimedean solid',
 'Calculus',
 'General relativity',
 'Empiricism',
 'Cauchy\xe2\x80\x93Riemann equations',
 'A. E. Housman',
 'Benoit Mandelbrot',
 'Carl Menger',
 'Austrian School',
 'Carl von Clausewitz',
 'Guy de Maupassant',
 'Arthur Schopenhauer',
 'Isaac Bashevis Singer',
 'Boolean algebra (structure)',
 'Feudalism',
 'Dorians',
 'Continuous function',
 'Banach space',
 'Compact space',
 'Georg Wilhelm Friedrich Hegel',
 'Hector',
 'Edmund Burke',
 'Euclidean geometry',
 'Integral',
 'Banach algebra',
 'Epictetus',
 'Ethics',
 'Gilgamesh',
 'Eurystheus',
 'Henri Bergson',
 'Dual polyhedron',
 'George Mason University',
 'Arthur Eddington',
 'Aesthetics',
 'Daedalus',
 'Amazons',
 'Apollo',
 'Asgard',
 'Gr\xc3\xadmnism\xc3\xa1l',
 'Albert Camus',
 'George Eliot',
 'Giuseppe Peano',
 'Complex number',
 'Aeacus',
 'G. E. Moore',
 'Evolutionary psychology',
 'Educational psychology',
 'Freyr',
 'Colin Maclaurin',
 'Gotthold Ephraim Lessing',
 'Existentialism',
 'Elagabalus',
 'Abdera, Thrace',
 'C*-algebra',
 'Classical liberalism',
 'Augustin-Louis Cauchy',
 'Continuity (fiction)',
 'List of islands of Greece',
 'Cyclades',
 'Battle of Marathon',
 'Gilles Deleuze',
 'Actaeon',
 'Horned God',
 'Gardnerian Wicca',
 'Coin',
 'Johann Gottlieb Fichte',
 'Cartesian coordinate system',
 'Heimskringla',
 'Dan Simmons',
 'Centaur',
 'Agamemnon',
 'Ajax (mythology)',
 'Felix Hausdorff',
 'Hausdorff dimension',
 'Fernando Pessoa',
 'Cogito ergo sum',
 'Countable set',
 'Andr\xc3\xa9 Gide',
 'Holomorphic function',
 'Annales School',
 'F\xc3\xa9lix Guattari',
 'Differential geometry',
 'Alcmene',
 'Freyja',
 'Hermetic Order of the Golden Dawn',
 "Euler's formula",
 'Exponential function',
 'Aegisthus',
 'Cassandra',
 'Alan Garner']
 '''
two = df[df['modularity_class'] == 7]
list(two['id']) #prints the following:
# computer science
#
'''
['Commodore International',
 'Apple Inc.',
 'Amiga',
 'Amiga 500',
 'Coleco',
 'Atari ST',
 'Atari',
 'Electronics',
 'Commodore 64',
 'Amiga 1000',
 'Doom (1993 video game)',
 'Free software',
 'GNU Lesser General Public License',
 'GNU',
 'Computer security',
 'Eric S. Raymond',
 'Apache HTTP Server',
 'GNU Compiler Collection',
 'BASIC',
 'GIMP',
 'Debian',
 'Software',
 'Internet',
 'Computer program',
 'Internet Engineering Task Force',
 'Ericsson',
 'Intel',
 'Internet Protocol',
 'Dot-com bubble',
 'Harmonic series (music)',
 'Fourier analysis',
 'Alpha',
 'DARPA',
 'Wikipedia:Status of FOLDOC import',
 'Intel 8086',
 'Industry Standard Architecture',
 'Free On-line Dictionary of Computing',
 'A',
 'EBCDIC',
 'ASCII',
 'Gatling gun',
 'Binary-coded decimal',
 'Association for Computing Machinery',
 'Donald Knuth',
 'Analytical Engine',
 'Integer',
 'Hexadecimal',
 'Charles Babbage',
 'BeOS',
 'IA-32',
 'Compaq',
 'Braille',
 'Character encoding',
 'Apple II series',
 'Apple I',
 'BIOS',
 'Hertz',
 'Apple III',
 'Apple II',
 'Global Positioning System',
 'Central processing unit',
 'Advanced Encryption Standard',
 'Functional programming',
 'Claude Shannon',
 'Data Encryption Standard',
 'Bill Joy',
 'Alan Turing',
 'Government Communications Headquarters',
 'Enigma machine',
 'Bletchley Park',
 'IBM Personal Computer',
 'Northrop F-5',
 'AGM-65 Maverick',
 'Huffman coding',
 'Digital signal processing',
 'Frequency',
 'Bandwidth (signal processing)',
 'Frequency modulation',
 'JavaScript',
 'Douglas Engelbart',
 'Baudot code',
 'Amplifier',
 'Game Boy Advance',
 'Handheld game console',
 'Game Boy Color',
 'C (programming language)',
 'Falklands War',
 'Hawker Siddeley Harrier',
 'COBOL',
 'Grace Hopper',
 'Brian Kernighan',
 'Dennis Ritchie',
 'Fortran',
 'AWK',
 'Computer science',
 'IP address',
 'Dynamic Host Configuration Protocol',
 'Internet protocol suite',
 'FAQ',
 'Domain Name System',
 'ICANN',
 'James Bond',
 'Ada Lovelace',
 'Computational complexity theory',
 'Atari 5200',
 'Atari 7800',
 'Atari 2600',
 'Intellivision',
 'Bluetooth',
 'APL (programming language)',
 'David Brewster',
 'Internet Explorer',
 'HTML',
 'Java applet',
 'GIF',
 'Berkeley, California',
 'American National Standards Institute',
 'Field-programmable gate array',
 'Entropy (information theory)',
 'Kolmogorov complexity',
 'Digital data',
 'Colossus computer',
 'History of computing hardware',
 'Common Lisp',
 'Digital Equipment Corporation',
 'Cyc',
 'Ada (programming language)',
 'Compiler',
 'Gopher (protocol)',
 'Intel 8088',
 'Parallel ATA',
 'Floppy disk',
 'Extended Industry Standard Architecture',
 'Intel 80286',
 'DEC Alpha',
 'Logical disjunction',
 'Itanium',
 'Lockheed C-130 Hercules',
 'Entscheidungsproblem',
 'Fibonacci number',
 'Herbert A. Simon',
 'Galois group',
 'Carl Friedrich Gauss',
 'McDonnell Douglas F-4 Phantom II',
 'McDonnell Douglas F-15 Eagle',
 'General Dynamics F-16 Fighting Falcon',
 'D',
 'G',
 'F',
 'Field (mathematics)',
 'AOL',
 'Ethernet',
 'Bill Gates',
 'Data compression',
 'Internet Control Message Protocol',
 'Fundamental theorem of arithmetic',
 'Euclidean algorithm',
 'Garbage collection (computer science)',
 'Intel 8080',
 'Bus (computing)',
 'Babylon 5',
 'Church\xe2\x80\x93Turing thesis',
 'HyperCard',
 'Amplitude modulation',
 'Bruce Perens',
 'AIM-120 AMRAAM',
 'Lockheed Martin F-35 Lightning II',
 'Intel 80486',
 'Intel 80386',
 'Austin, Texas',
 'Andrew S. Tanenbaum',
 'Wikipedia:Building Wikipedia membership',
 'Integrated development environment',
 'BIND',
 'Chinese remainder theorem',
 'IEEE 802.11',
 'Hypertext Transfer Protocol',
 'Graphical user interface',
 'Board of directors',
 'IPv6',
 'Common Gateway Interface',
 'Gaussian elimination',
 'B-tree',
 'B (programming language)',
 'CD-R',
 'Burroughs Corporation',
 'Blizzard Entertainment',
 'Computer multitasking',
 'DirectX',
 'Cygwin',
 'Computer memory',
 'Herman Hollerith',
 'Gigabyte',
 "G\xc3\xb6del's completeness theorem",
 'Analysis of algorithms',
 'Edsger W. Dijkstra',
 'ANSI C',
 'Computer animation',
 'IPv4',
 'Automated theorem proving',
 'Gauss (unit)',
 'Intel 80186',
 'Fighter aircraft',
 'BCPL',
 'Bulletin board system',
 'Enhanced Data Rates for GSM Evolution',
 'Diophantus',
 'IRIX',
 'Bessel function',
 'Grumman F-14 Tomcat',
 'Alan Kay',
 'Delta (letter)',
 'Decision problem',
 'ELIZA',
 'Eiffel (programming language)',
 'ALGOL',
 'Internet Relay Chat',
 'Bjarne Stroustrup',
 'Forth (programming language)',
 'Federal Information Processing Standards',
 'Advanced Micro Devices',
 'HTTPS',
 'Atari Jaguar',
 'Gregory Chaitin',
 'Artificial intelligence',
 'Fast Fourier transform',
 'Commodore 1541',
 'Infocom',
 'Assembly language',
 'Accumulator (computing)',
 'AIM-7 Sparrow',
 'AIM-54 Phoenix',
 'Golden ratio',
 'Computer monitor',
 'Integrated circuit',
 'Computer programming',
 '\xc3\x89variste Galois',
 'Distributed computing',
 'Rendering (computer graphics)',
 'Exxon',
 'Backward compatibility',
 'ColecoVision',
 'FidoNet',
 'Animation',
 'Garfield',
 'Adobe Systems',
 'Final Fantasy',
 'Amstrad CPC',
 'Decimal',
 'Data General Nova',
 'IBM mainframe',
 'Diophantine equation',
 "B\xc3\xa9zout's identity",
 'Euclidean domain',
 'General Packet Radio Service',
 'IEEE 802',
 'Array data structure']
 '''

two = df[df['modularity_class'] == 11]
list(two['id']) #prints the following:
